name: Build docker images for hub.docker.io and ghcr.io

# https://brunoscheufler.com/blog/2021-10-09-generating-dynamic-github-actions-workflows-with-the-job-matrix-strategy

on:
  push:
    branches:
      - main

jobs:

  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers-base:
          - base/alpine
          - base/debian
          - app/bashhub-server

    defaults:
      run:
        working-directory: ${{ matrix.containers-base }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_API_TOKEN }}

      - name: Generate image name
        run: echo "DOCKER_IMAGE_NAME=$(echo ${{ matrix.containers-base }} | tr '/' '-')" >> $GITHUB_ENV

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jakoberpf/${{ env.DOCKER_IMAGE_NAME }}

      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.containers-base }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jakoberpf/${{ env.DOCKER_IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  ghcr:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers-base:
          - base/alpine
          - base/debian
          - app/bashhub-server

    defaults:
      run:
        working-directory: ${{ matrix.containers-base }}

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image name
        run: echo "DOCKER_IMAGE_NAME=$(echo ${{ matrix.containers-base }} | tr '/' '-')" >> $GITHUB_ENV

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}

      # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      - name: Build and push Docker image to Github Registry
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.containers-base }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages