name: Build docker images

on:
  push:
    branches:
      - main

jobs:
  # This workflow contains a single job called "raudi"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers-base:
          - base/alpine
        # containers-ci: []
        # containers: []

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        working-directory: ${{ matrix.containers-base }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: jakoberpf/${{ matrix.containers-base }}:latest


